// src/lib/rental/seed-equipment.ts
import type { Equipment } from "./types";

export const seedEquipment: Equipment[] = [
  {
    id: "eq-mini-excavator-1t8",
    title: "Mini Excavator 1.8T",
    category: "earthmoving",
    brand: "Kubota",
    model: "U17 / Similar",
    images: ["/rental/mini-excavator.jpg"],
    shortDesc: "Compact excavator for tight-access trenching and site works.",
    specs: {
      "Operating weight": "1.7–1.9T",
      "Max dig depth": "~2.3m",
      "Width": "~990mm",
      "Power": "Diesel",
    },
    totalUnits: 3,
    isPublished: true,
    pricing: { minDays: 1, dayRate: 280, weekRate: 1500, monthRate: 5200, deposit: 800 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "eq-scissor-lift-8m",
    title: "Scissor Lift 8m (Electric)",
    category: "lifting",
    brand: "JLG",
    model: "1930ES / Similar",
    images: ["/rental/scissor-lift.jpg"],
    shortDesc: "Indoor/outdoor low-noise scissor lift for maintenance works.",
    specs: {
      "Platform height": "8m",
      "Max load": "230kg",
      "Power": "Electric",
      "Use": "Flat ground",
    },
    totalUnits: 2,
    isPublished: true,
    pricing: { minDays: 1, dayRate: 220, weekRate: 1200, monthRate: 4200, deposit: 600 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "eq-generator-5kva",
    title: "Portable Generator 5kVA",
    category: "power",
    brand: "Honda",
    model: "EU65is / Similar",
    images: ["/rental/generator.jpg"],
    shortDesc: "Reliable portable generator for sites and event power needs.",
    specs: {
      Output: "5kVA",
      "Fuel type": "Petrol",
      "Noise level": "Low-noise inverter",
      "Run time": "Up to ~8h (varies)",
    },
    totalUnits: 6,
    isPublished: true,
    pricing: { minDays: 1, dayRate: 90, weekRate: 480, monthRate: 1600, deposit: 200 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "eq-concrete-mixer-120l",
    title: "Concrete Mixer 120L",
    category: "concreting",
    brand: "Generic",
    model: "120L Drum",
    images: ["/rental/concrete-mixer.jpg"],
    shortDesc: "Portable drum mixer for small-to-medium concreting jobs.",
    specs: {
      Capacity: "120L",
      "Power": "Electric",
      "Drum": "Steel",
      "Mobility": "Wheeled",
    },
    totalUnits: 4,
    isPublished: false,
    pricing: { minDays: 1, dayRate: 35, weekRate: 160, monthRate: 520, deposit: 80 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "eq-plate-compactor-90kg",
    title: "Plate Compactor 90kg",
    category: "compaction",
    brand: "Wacker Neuson",
    model: "DPU / Similar",
    images: ["/rental/plate-compactor.jpg"],
    shortDesc: "Compactor for soil/sand/base layer compaction and patch works.",
    specs: {
      "Operating weight": "90kg",
      "Fuel type": "Petrol/Diesel",
      "Base plate": "Standard",
      Use: "Outdoor",
    },
    totalUnits: 5,
    isPublished: true,
    pricing: { minDays: 1, dayRate: 55, weekRate: 260, monthRate: 850, deposit: 120 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
